### ISSUE TITLE
Update createStudent to accept password

### ISSUE THREAD

**Issue by percimar** [MarwanAlsharafi/INFS3203-Project-3#1]
- [x] Create a git branch for this feature
- [x] Update createStudent to create a password for the created student, the password must be automatically generated and encrypted with base64. 
- [x] Edit the menu for this function to validate inputs (keep asking age/id until user inputs a number)
- [x] Create a test plan for this function, and implement the test cases.
- [x] Create a pull request to merge your branch into main

**Comment by huzaifa-60095630** [comment]
Closed in #6
